// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

library Errors {
    error MarketState();
    error MarketNotFound();
    error TVL();
    error Fail();
    error OnlyStakeForYear();
    error StaleNFT();
    error TokenBlocked(uint256 tokenId);
    error InvalidAnonStakingAddress();
    error NotOperator();
    error PenaltyTokenNotSet();
    error CannotDisputeWithPendingStatus();
    error ReasonTooLong();
    error DisputeAlreadyOpened();
    error CollateralAmountTooLarge();
    error NotTheDisputer();
    error AlreadyTaken();
    error CannotClaimCollateral();
    error OnlyAvailableOnHomeChain();
    error EmptyArray();
    error DisputeNotActive();
    error VotingPeriodEnded();
    error CannotVoteForPending();
    error EmptyTokenIdsArray();
    error NotNFTOwnerOrApproved();
    error NFTLockedVotingCooldown();
    error NFTExpiredInStakingContract();
    error NoValidVotes();
    error UseWithdrawToCrossChain();
    error UseWithdrawToOnHomeChain();
    error StakeRewardsOnlyOnHomeChain();
    error DisputeNotResolved();
    error NoVotesCast();
    error TokenIdDidNotVote();
    error AlreadyClaimedForTokenId();
    error NoRewardsToClaim();
    error VotingPeriodNotEnded();
    error NoOneVoted();
    error TopUpFailed();
    error InvalidAddress();
    error NoPenaltySet();
    error TooEarly();
    error NFTLockedDisputeResolution();
    error NotOwnerOrApproved();
    error CanOnlyUnwrapOnHomeChain();
    error InvalidMessageType();
}
